### PR TITLE
feat: add a part of zh-Hans translation for CSS2021 result

### PR DESCRIPTION
**Pull request by shadowings-zy**
Hi!

One year later i'm back! 
I added a part of the translation of zh-Hans for CSS2021.

Mainly translated: 
(1) content of the sidebar
(2) introduction
(3) awards
(4) conclusion

cc @SachaG

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! I invited you so you should have the rights to manage this repo and merge in the PR yourself, let me know if it works!

**Comment by shadowings-zy** [comment]
> Thanks! I invited you so you should have the rights to manage this repo and merge in the PR yourself, let me know if it works!

I received the e-mail and join the organization, Thanks!

**Comment by shadowings-zy** [comment]
截屏2021-12-30 14 46 24

But I can not merge this PR because I need a maintainer to approve running workflows

**Comment by SachaG** [comment]
Sorry, should be fixed now.

**Comment by shadowings-zy** [comment]
I merged this PR

**Pull request merged**
